"""добавлены даты в Levels на одного человека

Revision ID: 1171c78c2ddd
Revises: 4693975fdb82
Create Date: 2023-04-22 18:20:56.987929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1171c78c2ddd'
down_revision = '4693975fdb82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
