"""добавление в бд колонкок с юзером

Revision ID: 44e4c80e4a9f
Revises: 1171c78c2ddd
Create Date: 2023-04-22 19:11:50.985964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e4c80e4a9f'
down_revision = '1171c78c2ddd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('levels', sa.Column('level_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'level_number')
    op.drop_column('levels', 'user_id')
    # ### end Alembic commands ###
