"""сохранение цели пользователя в бд

Revision ID: db26d2b8096c
Revises: ff94e5ce0c27
Create Date: 2023-04-28 21:35:33.445161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db26d2b8096c'
down_revision = 'ff94e5ce0c27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
