"""date of repetition in Levels table

Revision ID: e6d7be2564c9
Revises: 56a49d0f2dc2
Create Date: 2023-04-10 23:54:15.774646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d7be2564c9'
down_revision = '56a49d0f2dc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('levels')
    op.drop_table('cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('front_side', sa.VARCHAR(), nullable=True),
    sa.Column('back_side', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['level'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('days_period', sa.INTEGER(), nullable=True),
    sa.Column('repetition_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
