"""добавление id пользователя в таблицу карт

Revision ID: ff94e5ce0c27
Revises: 44e4c80e4a9f
Create Date: 2023-04-26 10:16:18.848405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff94e5ce0c27'
down_revision = '44e4c80e4a9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'levels', ['level'], ['level_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'user_id')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'levels', ['level'], ['id'])
    # ### end Alembic commands ###
